# Generated by Django 4.0.2 on 2022-05-27 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_link',
        ),
    ]
